.PHONY: all clean

include ../rules/Makefile.conf
include ../rules/Makefile.common

# ==== sources and targets ====

SRC:=\
	unmht.cc \
	JSWrapper.cc \
	conv.m

TARGET_LIB:=unmht.a

# ==== build rules ====

#SILENT:=@
include ../rules/Makefile.build
